### ISSUE TITLE
Set up basic infrastructure to run scrapers

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/planning#10]
@jamesturk and my initial thought was to have an Open States AMI prepped, and then each state would have a time-triggered Lambda that would execute overnight, by instantiating the AMI into an EC2.

But before executing this, I'll chew over a few other ideas If anyone here has further thoughts on a simple AWS system for this, chime on in!

Ideally, I'll also create this using a CloudFormation template or the like, rather than just manually.

This is definitely a short-term implementation; in the medium-term, we'll probably return to @paultag's [Moxie](https://github.com/paultag/moxie).

**Comment by mileswwatkins** [comment]
After bouncing the idea of a few more people, the thought is to make the image Dockerized, build and post it publicly to Docker Hub each time there's a new push to master in either Billy or OS repos, and then run it on AWS Data Pipeline (scheduled) or using the above-mentioned Lambda+EC2 instantiation.

**Comment by jamesturk** [comment]
I'm all for this, any idea if we'll have some that'll have issues running
fully dockerized? I'm mostly concerned off the top of my head about CA and
whichever have abiword dependencies.

Maybe this was already addressed during moxieization though.

On Dec 19, 2016 2:55 PM, "Miles Watkins" <notifications@github.com> wrote:

After bouncing the idea of a few more people, the thought is to make the
image Dockerized, build and post it publicly to Docker Hub each time
there's a new push to master in either Billy or OS repos, and then run it
on AWS Data Pipeline (scheduled) or using the above-mentioned Lambda+EC2
instantiation.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openstates/planning/issues/10#issuecomment-268061896>,
or mute the thread

**Comment by mileswwatkins** [comment]
Yeah, IIRC this was handled. BTW, for CI systems (to generate the Docker images), any preferences, Travis vs Circle vs …?

**Comment by jamesturk** [comment]
I'm trying out the hub.docker.com automatic builds, openstates/billy and
openstates/openstates are building now

**Comment by jamesturk** [comment]
basic infrastructure is in place, tracking issues on that repo
