### ISSUE TITLE
Server Architecture

### ISSUE THREAD

**Issue by jamesturk** [openstates/planning#3]
Right Now:

| Server  | Size | Notes |
| ------- | ---- | ------ |
| OpenStates.org  | m3.large?  | possibly smaller, better use of caching |
| ElasticSearch  | m3.xlarge?  | kill in favor of postgres full text? |
| MongoDB  | m3.large?  | kill in favor of postgres |
| moxie  | m3.large?  | keep, evaluate t2 burst instances? |
| Postgres  | m3.large?  | maybe needs to grow since this is where the GIS and FT search will be |

**Comment by estaub** [comment]
I'm new, so I'm writing from ignorance.  But it seemed to me that Sunrise was taking on a lot by being the sole hosting entity.  Consider whether it might make sense to have a distributed architecture, where someone could easily pull down a project and launch a server that keeps itself up-to-date with an "origin" server.  For fastest adoption, I'd consider using Node.js-based tech stack, but YMMD.

If this makes any sense, it might drive toward leaving things on MongoDB, because I think you'd get more and quicker server launches.

I don't see a need, but you might even want to not have a single "root" server, but instead potentially have different authority roots for different states.

**Comment by jamesturk** [comment]
I think there's some merit here for sure, but a distributed architecture would be a huge shift from how things work now and our most precious resource is time.

Actually closing this issue out for now, we have a stripped down architecture that'll keep us alive in the short term while we iterate on migration to a more stable/flexible future architecture.
