### ISSUE TITLE
Proposal: State Prioritization

### ISSUE THREAD

**Issue by jamesturk** [openstates/planning#4]
To ease maintenance burden we would adopt a formal policy of prioritizing states with an eye towards sustainability.

Our hope would be that once the project reached a certain stride it would be maintainable without these kinds of trade-offs, but in the name of pragmatism we'd take the following into account:
- Data Quality - higher quality data = more updates
- Popularity - not population, but likely correlated.  the more people using a state's data the more attention it'd get
- Donations - yep, you can bribe people to get your state to the front of the line.

Ideally I'd like to somewhat formalize this, especially the role donations might play.  What (if any) guarantee does a donation get you?  What do we think we can provide as baseline support (24 hour turnaround? No. 1 week? let's talk)?

**Comment by showerst** [comment]
It's also worth looking at how the sessions fall, e.g. with Texas where they'll only be updating from Jan -> May 2017 then do nothing for 2 more years. 

The maintenance burden also differs significantly, some states rarely change (CA, NH now that we're using their sql database), others require constant patching (New york, Ohio).

I have a set of probably 5-10 openstates patches to bring every legislature's bill scrapers up to 'working' status since activity on that repo stopped a few months ago. Many of the legislature, vote, and committee scrapers aren't working.

**Comment by jamesturk** [comment]
this ticket feels obsolete for now, definitely things to return to at some point, but the issue of prioritization was taken care of for now.  maintenance prioritization will be a different thing, but we'lls ee how that plays out
