### ISSUE TITLE
Question on the plans for Pupa

### ISSUE THREAD

**Issue by showerst** [openstates/planning#7]
With respect to moving the state scrapers over to Pupa, is the plan to port the openstates code over, and then make the necessary changes to fit the Pupa model? Is it necessary for some reason (licensing, code maintainability, etc) to write them from scratch?

I'd be willing to get started on that code port soon and try to knock out a handful of states a week, if it meant getting the scraping infrastructure running on Pupa before the new sessions really get going.

**Comment by jamesturk** [comment]
We're still sorting it out, but I think we'll bring scrapers over to pupa (for maintainability/eventual ease of server maintenance/the nicer data model/etc.) and have the data flow back into the billy data model for a while so that OpenStates.org and the v1 API can work while we port other stuff.

They don't have to be written from scratch, some might be easier to, but I imagine a lot of them can be ported without too much effort.  There's a florida one checked in here now, I think ideally we'll split them into new repos.  If there's one you want to start with for now let me know and I'll make the repo and give you the appropriate access, thanks!

**Comment by showerst** [comment]
I have patches to Openstates to bring almost all the existing states current, most of which are just changes to __init.py__ -- though I've had to do a few total rewrites. I'll go through the sheet and add that data tomorrow.

I think the 'move them to pupa without working to integrate tim's 2017 additions' is the right move, but here's [my openstates repo](https://github.com/showerst/openstates) in case anyone wants to use working 2017 changes as a baseline.

**Comment by jamesturk** [comment]
closing this one out, we'll write up Pupa migration plans soon now that we're getting back up to speed
